name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: rustup update && rustup install 1.65.0 && rustup default 1.65.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
